# Generated by Django 4.0.4 on 2022-05-17 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_paper', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='user',
            new_name='authorUser',
        ),
        migrations.RenameField(
            model_name='postcategory',
            old_name='categ',
            new_name='categThrough',
        ),
        migrations.RenameField(
            model_name='postcategory',
            old_name='post',
            new_name='postThrough',
        ),
    ]
